apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: build-container-image-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
spec:
  entrypoint: build
  serviceAccountName: argo
  templates:
  - name: build
    dag:
      tasks:
      - name: build
        templateRef:
          name: build-container-image
          template: build-kaniko-git
          clusterScope: false
        arguments:
          parameters:
          - name: app_repo
            value: git://github.com/danialdehkordi/k8s-native-cicd
          - name: container_image
            value: europe-west3-docker.pkg.dev/coen-danial-dehkordi/artifact-repository/test-image
          - name: container_tag
            value: "1.0.0"